const data = [
  {
    id: 0,
    name: "The Web Developer Bootcamp",
    instructor: "Colt Steele",
    img: "https://img-a.udemycdn.com/course/240x135/625204_436a_2.jpg",
    rating: 5,
    ratingCount: 10000,
    price: 20,
  },
  {
    id: 1,
    name: "The Complete JavaScript Course 2020: Build Real Projects!",
    instructor: "Jonas Schmedtmann",
    img: "https://img-a.udemycdn.com/course/240x135/851712_fc61_5.jpg",
    rating: 5,
    ratingCount: 9000,
    price: 15,
  },
  {
    id: 2,
    name: "Angular - The Complete Guide (2020 Edition)",
    instructor: "Maximilian Schwarzmuller",
    img: "https://img-a.udemycdn.com/course/240x135/756150_c033_2.jpg",
    rating: 5,
    ratingCount: 9560,
    price: 12,
  },
  {
    id: 3,
    name: "The Web Developer Bootcamp",
    instructor: "Colt Steele",
    img: "https://img-a.udemycdn.com/course/240x135/625204_436a_2.jpg",
    rating: 5,
    ratingCount: 10000,
    price: 20,
  },
  {
    id: 4,
    name: "The Complete JavaScript Course 2020: Build Real Projects!",
    instructor: "Jonas Schmedtmann",
    img: "https://img-a.udemycdn.com/course/240x135/851712_fc61_5.jpg",
    rating: 5,
    ratingCount: 9000,
    price: 15,
  },
  {
    id: 5,
    name: "Angular - The Complete Guide (2020 Edition)",
    instructor: "Maximilian Schwarzmuller",
    img: "https://img-a.udemycdn.com/course/240x135/756150_c033_2.jpg",
    rating: 5,
    ratingCount: 9560,
    price: 12,
  },
  {
    id: 6,
    name: "The Web Developer Bootcamp",
    instructor: "Colt Steele",
    img: "https://img-a.udemycdn.com/course/240x135/625204_436a_2.jpg",
    rating: 5,
    ratingCount: 10000,
    price: 20,
  },
  {
    id: 7,
    name: "The Complete JavaScript Course 2020: Build Real Projects!",
    instructor: "Jonas Schmedtmann",
    img: "https://img-a.udemycdn.com/course/240x135/851712_fc61_5.jpg",
    rating: 5,
    ratingCount: 9000,
    price: 15,
  },
  {
    id: 8,
    name: "Angular - The Complete Guide (2020 Edition)",
    instructor: "Maximilian Schwarzmuller",
    img: "https://img-a.udemycdn.com/course/240x135/756150_c033_2.jpg",
    rating: 5,
    ratingCount: 9560,
    price: 12,
  },
];

export default data;

const template = [
  {
    id: 5,
    name: "",
    instructor: "",
    img: "",
    rating: 0,
    ratingCount: 0,
    price: 1,
  },
  {
    id: 6,
    name: "",
    instructor: "",
    img: "",
    rating: 0,
    ratingCount: 0,
    price: 1,
  },
  {
    id: 7,
    name: "",
    instructor: "",
    img: "",
    rating: 0,
    ratingCount: 0,
    price: 1,
  },
  {
    id: 8,
    name: "",
    instructor: "",
    img: "",
    rating: 0,
    ratingCount: 0,
    price: 1,
  },
  {
    id: 9,
    name: "",
    instructor: "",
    img: "",
    rating: 0,
    ratingCount: 0,
    price: 1,
  },
];
